/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkerViewIndexImport } from './routes/worker-view/index'
import { Route as WeekView2IndexImport } from './routes/week-view2/index'
import { Route as WeekViewIndexImport } from './routes/week-view/index'
import { Route as ScenariosIndexImport } from './routes/scenarios/index'
import { Route as MapViewIndexImport } from './routes/map-view/index'
import { Route as DailyPlanIndexImport } from './routes/daily-plan/index'
import { Route as CompanyConfigIndexImport } from './routes/company-config/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkerViewIndexRoute = WorkerViewIndexImport.update({
  id: '/worker-view/',
  path: '/worker-view/',
  getParentRoute: () => rootRoute,
} as any)

const WeekView2IndexRoute = WeekView2IndexImport.update({
  id: '/week-view2/',
  path: '/week-view2/',
  getParentRoute: () => rootRoute,
} as any)

const WeekViewIndexRoute = WeekViewIndexImport.update({
  id: '/week-view/',
  path: '/week-view/',
  getParentRoute: () => rootRoute,
} as any)

const ScenariosIndexRoute = ScenariosIndexImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRoute,
} as any)

const MapViewIndexRoute = MapViewIndexImport.update({
  id: '/map-view/',
  path: '/map-view/',
  getParentRoute: () => rootRoute,
} as any)

const DailyPlanIndexRoute = DailyPlanIndexImport.update({
  id: '/daily-plan/',
  path: '/daily-plan/',
  getParentRoute: () => rootRoute,
} as any)

const CompanyConfigIndexRoute = CompanyConfigIndexImport.update({
  id: '/company-config/',
  path: '/company-config/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/company-config/': {
      id: '/company-config/'
      path: '/company-config'
      fullPath: '/company-config'
      preLoaderRoute: typeof CompanyConfigIndexImport
      parentRoute: typeof rootRoute
    }
    '/daily-plan/': {
      id: '/daily-plan/'
      path: '/daily-plan'
      fullPath: '/daily-plan'
      preLoaderRoute: typeof DailyPlanIndexImport
      parentRoute: typeof rootRoute
    }
    '/map-view/': {
      id: '/map-view/'
      path: '/map-view'
      fullPath: '/map-view'
      preLoaderRoute: typeof MapViewIndexImport
      parentRoute: typeof rootRoute
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosIndexImport
      parentRoute: typeof rootRoute
    }
    '/week-view/': {
      id: '/week-view/'
      path: '/week-view'
      fullPath: '/week-view'
      preLoaderRoute: typeof WeekViewIndexImport
      parentRoute: typeof rootRoute
    }
    '/week-view2/': {
      id: '/week-view2/'
      path: '/week-view2'
      fullPath: '/week-view2'
      preLoaderRoute: typeof WeekView2IndexImport
      parentRoute: typeof rootRoute
    }
    '/worker-view/': {
      id: '/worker-view/'
      path: '/worker-view'
      fullPath: '/worker-view'
      preLoaderRoute: typeof WorkerViewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company-config': typeof CompanyConfigIndexRoute
  '/daily-plan': typeof DailyPlanIndexRoute
  '/map-view': typeof MapViewIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/week-view': typeof WeekViewIndexRoute
  '/week-view2': typeof WeekView2IndexRoute
  '/worker-view': typeof WorkerViewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-config': typeof CompanyConfigIndexRoute
  '/daily-plan': typeof DailyPlanIndexRoute
  '/map-view': typeof MapViewIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/week-view': typeof WeekViewIndexRoute
  '/week-view2': typeof WeekView2IndexRoute
  '/worker-view': typeof WorkerViewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/company-config/': typeof CompanyConfigIndexRoute
  '/daily-plan/': typeof DailyPlanIndexRoute
  '/map-view/': typeof MapViewIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/week-view/': typeof WeekViewIndexRoute
  '/week-view2/': typeof WeekView2IndexRoute
  '/worker-view/': typeof WorkerViewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-config'
    | '/daily-plan'
    | '/map-view'
    | '/scenarios'
    | '/week-view'
    | '/week-view2'
    | '/worker-view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-config'
    | '/daily-plan'
    | '/map-view'
    | '/scenarios'
    | '/week-view'
    | '/week-view2'
    | '/worker-view'
  id:
    | '__root__'
    | '/'
    | '/company-config/'
    | '/daily-plan/'
    | '/map-view/'
    | '/scenarios/'
    | '/week-view/'
    | '/week-view2/'
    | '/worker-view/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyConfigIndexRoute: typeof CompanyConfigIndexRoute
  DailyPlanIndexRoute: typeof DailyPlanIndexRoute
  MapViewIndexRoute: typeof MapViewIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  WeekViewIndexRoute: typeof WeekViewIndexRoute
  WeekView2IndexRoute: typeof WeekView2IndexRoute
  WorkerViewIndexRoute: typeof WorkerViewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyConfigIndexRoute: CompanyConfigIndexRoute,
  DailyPlanIndexRoute: DailyPlanIndexRoute,
  MapViewIndexRoute: MapViewIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  WeekViewIndexRoute: WeekViewIndexRoute,
  WeekView2IndexRoute: WeekView2IndexRoute,
  WorkerViewIndexRoute: WorkerViewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/company-config/",
        "/daily-plan/",
        "/map-view/",
        "/scenarios/",
        "/week-view/",
        "/week-view2/",
        "/worker-view/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/company-config/": {
      "filePath": "company-config/index.tsx"
    },
    "/daily-plan/": {
      "filePath": "daily-plan/index.tsx"
    },
    "/map-view/": {
      "filePath": "map-view/index.tsx"
    },
    "/scenarios/": {
      "filePath": "scenarios/index.tsx"
    },
    "/week-view/": {
      "filePath": "week-view/index.tsx"
    },
    "/week-view2/": {
      "filePath": "week-view2/index.tsx"
    },
    "/worker-view/": {
      "filePath": "worker-view/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
