/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkerViewIndexImport } from './routes/worker-view/index'
import { Route as ScenariosIndexImport } from './routes/scenarios/index'
import { Route as MapViewIndexImport } from './routes/map-view/index'
import { Route as CompanyConfigIndexImport } from './routes/company-config/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkerViewIndexRoute = WorkerViewIndexImport.update({
  id: '/worker-view/',
  path: '/worker-view/',
  getParentRoute: () => rootRoute,
} as any)

const ScenariosIndexRoute = ScenariosIndexImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRoute,
} as any)

const MapViewIndexRoute = MapViewIndexImport.update({
  id: '/map-view/',
  path: '/map-view/',
  getParentRoute: () => rootRoute,
} as any)

const CompanyConfigIndexRoute = CompanyConfigIndexImport.update({
  id: '/company-config/',
  path: '/company-config/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/company-config/': {
      id: '/company-config/'
      path: '/company-config'
      fullPath: '/company-config'
      preLoaderRoute: typeof CompanyConfigIndexImport
      parentRoute: typeof rootRoute
    }
    '/map-view/': {
      id: '/map-view/'
      path: '/map-view'
      fullPath: '/map-view'
      preLoaderRoute: typeof MapViewIndexImport
      parentRoute: typeof rootRoute
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosIndexImport
      parentRoute: typeof rootRoute
    }
    '/worker-view/': {
      id: '/worker-view/'
      path: '/worker-view'
      fullPath: '/worker-view'
      preLoaderRoute: typeof WorkerViewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company-config': typeof CompanyConfigIndexRoute
  '/map-view': typeof MapViewIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/worker-view': typeof WorkerViewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-config': typeof CompanyConfigIndexRoute
  '/map-view': typeof MapViewIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/worker-view': typeof WorkerViewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/company-config/': typeof CompanyConfigIndexRoute
  '/map-view/': typeof MapViewIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/worker-view/': typeof WorkerViewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-config'
    | '/map-view'
    | '/scenarios'
    | '/worker-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company-config' | '/map-view' | '/scenarios' | '/worker-view'
  id:
    | '__root__'
    | '/'
    | '/company-config/'
    | '/map-view/'
    | '/scenarios/'
    | '/worker-view/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyConfigIndexRoute: typeof CompanyConfigIndexRoute
  MapViewIndexRoute: typeof MapViewIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  WorkerViewIndexRoute: typeof WorkerViewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyConfigIndexRoute: CompanyConfigIndexRoute,
  MapViewIndexRoute: MapViewIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  WorkerViewIndexRoute: WorkerViewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/company-config/",
        "/map-view/",
        "/scenarios/",
        "/worker-view/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/company-config/": {
      "filePath": "company-config/index.tsx"
    },
    "/map-view/": {
      "filePath": "map-view/index.tsx"
    },
    "/scenarios/": {
      "filePath": "scenarios/index.tsx"
    },
    "/worker-view/": {
      "filePath": "worker-view/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
