name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # FRONTEND
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test || echo "No frontend tests found, skipping"

      # BACKEND
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        run: |
          if ls test_*.py 1> /dev/null 2>&1; then
            pytest
          else
            echo "No backend tests found, skipping"

      # FRONTEND DEPLOY
      - name: Deploy Frontend
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Starting frontend deployment..."

      # BACKEND DEPLOY
      - name: Deploy Backend
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Starting backend deployment..."
