name: CI/CD Backend

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        run: |
          if ls test_*.py 1> /dev/null 2>&1; then
            pytest
          else
            echo "No backend tests found, skipping"

      - name: Deploy Backend
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Starting backend deployment..."
