name: Deploy FastAPI Backend to Google VM

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Ensure folder exists and has correct permissions
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "
            sudo mkdir -p /opt/backend-deploy &&
            sudo chown -R root:deployers /opt/backend-deploy &&
            sudo chmod -R 775 /opt/backend-deploy &&
            sudo chmod g+s /opt/backend-deploy
          "

      - name: Remove old backend code
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} \
            "rm -rf /opt/backend-deploy/backend"

      - name: Upload backend code
        run: |
          scp -i ~/.ssh/id_rsa -r ./backend ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/opt/backend-deploy/

      - name: Upload .env file
        run: |
          cat <<EOF > temp.env
          GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          # Add more environment variables here if needed
          EOF

          scp -i ~/.ssh/id_rsa temp.env ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/opt/backend-deploy/backend/.env
          rm temp.env

      - name: Deploy backend with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} \
            "cd /opt/backend-deploy && docker-compose -f backend/docker-compose.backend.yml up -d --build"
